version: '3.8'

services:
  web:
    build:
      context: ../LLM
    volumes:
      - ../LLM:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  frontend:
    build:
      context: ../frontend
    ports:
      - "8080:8080"
    command: ["npm", "run", "serve"]