services:
  web:
    build:
      context: ./
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ["python", "/app/manage.py", "runserver", "0.0.0.0:8000"]
    working_dir: /app

  frontend:
    build:
      context: ../frontend
    ports:
      - "8080:8080"
    command: ["npm", "run", "serve"]